steps:
  - name: "gcr.io/cloud-builders/go"
    args: ["install", "github.com/bigjr/spintest"]
    env: ["PROJECT_ROOT=github.com/bigjr/spintest"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/jr-kick-off-2018/spinnaker-1:$REVISION_ID", "-f", "Dockerfile", "."]
images:
  - "gcr.io/jr-kick-off-2018/spinnaker-1:$REVISION_ID"
